// Normative expected cases. Bind these to production APIs/adapters; this file
// neither resolves a tuple nor models an owner store. Used by gated runners.
export const cases = {
  codecs: [
    {id:'preserve-configured-surrounding-whitespace',input:{kind:'fields',fields:{model:' catalog-id '}},expected:{kind:'fields',fields:{model:' catalog-id '}},encodeExpected:{kind:'fields',fields:{model:' catalog-id '}}},
    {id:'reject-all-whitespace-model',input:{kind:'fields',fields:{model:'   '}},rejected:'malformed'},
    {id:'delete-cleared-key',input:{kind:'fields',fields:{}},encodeExpected:{kind:'inherit'}},
    {id:'delete-empty-provider-entry',input:{kind:'by-provider',entries:{p:{}}},encodeExpected:{kind:'inherit'}},
    ...[{kind:'wat'}, {kind:'inherit',unknown:true}, {kind:'fields',fields:{model:''}}, {kind:'fields',fields:{serviceTier:'fast'}}, {kind:'by-provider',entries:{p:{providerId:'q'}}}, {kind:'by-provider',entries:{p:{serviceTier:'default'}}}].map((input,i)=>({id:`malformed-${i}`,input,rejected:'malformed'})),
    {id:'allowed-shapes',input:{kind:'tuple',selection:{providerId:'p',model:'m',reasoningLevel:'low'}},choiceKinds:['inherit','fields'],rejected:'choice-kind-not-allowed'},
    {id:'unavailable-is-retained',input:{kind:'tuple',selection:{providerId:'gone',model:'gone',reasoningLevel:'low'}},decodeExpected:'valid-shape',readEligibility:'unverified'},
    {id:'no-legacy-blank-conversion-in-codec',input:{kind:'fields',fields:{model:'',reasoningLevel:'inherit'}},rejected:'malformed'},
  ],
  cascade: [
    {id:'owner-no-override-fast-path',fields:{},permissionOverride:undefined,expectedCatalogCalls:0,nativeBoundary:true},
    {id:'owner-permission-only-trigger',fields:{},permissionOverride:'auto',expectedCatalogCalls:1,nativeBoundary:true},
    {id:'same-provider-missing-inherited-model',fields:{},caller:{providerId:'p',model:'missing',reasoningLevel:'high'},defaultRow:{model:'default-exec',defaultReasoningEffort:'low'},expected:{providerId:'p',model:'default-exec',reasoningLevel:'low'}},
    {id:'changed-provider-default-reasoning',fields:{providerId:'q'},expectedReasoning:'row-default'},
    {id:'changed-model-default-reasoning',fields:{model:'alias-id'},matchedRow:{id:'alias-id',model:'exec-model'},expectedModel:'exec-model',expectedReasoning:'row-default',storedModel:'alias-id'},
    {id:'same-model-retains-reasoning',fields:{model:'same-model'},expectedReasoning:'caller'},
    {id:'unsupported-inherited-reasoning',fields:{providerId:'p'},rejected:'reasoning-unsupported'},
    {id:'selected-only-included',fields:{model:'selected-id'},expectedCandidatePool:'models+selected-only'},
    {id:'tier-supported',callerTier:'fast',supportsServiceTier:true,expectedTier:'fast'},
    {id:'tier-supported-null',callerTier:null,supportsServiceTier:true,expectedTier:'default'},
    {id:'tier-unsupported',callerTier:'fast',supportsServiceTier:false,expectedTier:'omitted'},
    {id:'permissions-remain-owner-side',expected:'permission-ceiling-and-support-run-after-cascade',nativeBoundary:true},
  ],
  validation: [
    {id:'rosetta-default-unsupported',policy:'rosetta',tier:'default',supportsServiceTier:false,accepted:true},
    {id:'rosetta-fast-unsupported',policy:'rosetta',tier:'fast',supportsServiceTier:false,rejected:'service-tier-unsupported'},
    {id:'rtd-default-unsupported',policy:'rtd',tier:'default',supportsServiceTier:false,rejected:'service-tier-unsupported'},
    {id:'rtd-default-not-listed',policy:'rtd',tier:'default',supportsServiceTier:true,serviceTiers:[{id:'fast'}],rejected:'service-tier-unsupported'},
    {id:'rtd-fast-not-listed',policy:'rtd',tier:'fast',supportsServiceTier:true,serviceTiers:[{id:'default'}],rejected:'service-tier-unsupported'},
    {id:'rtd-null-omitted',policy:'rtd',tier:null,supportsServiceTier:false,accepted:true,nativeBoundary:true},
    {id:'selected-only-new-choice',policy:'rosetta',selectedOnly:true,rejected:'selected-only-not-offered'},
    {id:'selected-only-caller',policy:'perspectives',selectedOnly:true,accepted:true},
    {id:'catalog-error-rosetta',policy:'rosetta',modelLoadError:true,rejected:'catalog-unavailable'},
    {id:'catalog-error-caller',policy:'perspectives',modelLoadError:true,matchingRowPresent:true,accepted:true},
    {id:'route-qualifier-is-not-execution-provider',providerId:'pi',routeProviderId:'underlying',policy:'rosetta',rejected:'model-unavailable'},
    {id:'caller-route-qualifier-ignored',providerId:'pi',routeProviderId:'underlying',policy:'perspectives',accepted:true},
    {id:'differing-host-environment-catalogs',hostModels:['host-model'],environmentModels:['env-model'],selectionModel:'env-model',hostRejected:'model-unavailable',environmentAccepted:true},
    {id:'workspace-gates-owner-side',rosetta:'requires-environment-route',rtd:'requires-project-default-profile',nativeBoundary:true},
  ],
  byProvider: [
    {id:'absent-entry',choice:{kind:'by-provider',entries:{q:{model:'q-model'}}},basis:{providerId:'p',model:'child-model',boundary:'fork-child'},expected:{kind:'no-override'}},
    {id:'reasoning-child-not-source',choice:{kind:'by-provider',entries:{p:{reasoningLevel:'high'}}},basis:{providerId:'p',model:'child-model',boundary:'fork-child'},sourceModel:'source-model',childSupported:['low'],sourceSupported:['high'],rejected:'reasoning-unsupported'},
    {id:'unknown-field',offered:{model:'unknown'},entry:{model:'m'},rejected:'field-not-offered'},
    {id:'blocked-provider',offered:{blocked:['catalog-empty']},entry:{model:'m'},rejected:'provider-blocked'},
    {id:'missing-provider-capability',offered:undefined,entry:{model:'m'},rejected:'provider-blocked'},
    {id:'create-reasoning-only-unknown',boundary:'create',entry:{reasoningLevel:'high'},offered:{reasoningLevel:'unknown'},rejected:'field-not-offered'},
    {id:'create-reasoning-only-demonstrated',boundary:'create',entry:{reasoningLevel:'high'},offered:{reasoningLevel:'demonstrated'},expectedFields:{reasoningLevel:'high'},deferredChecks:['reasoning-vs-native-default-model']},
    {id:'source-estimate-provisional',sourceRejects:true,childAccepts:true,expected:'source-estimate-cannot-reject-anchored-child',nativeBoundary:true},
  ],
  protocol: [
    {id:'v1-v2',versions:[1,2],expectedVersion:1}, {id:'v2-only',versions:[2],expected:'incompatible-version',decodeRoles:false},
    ...[[],[0],[1.5],Array(17).fill(1)].map((versions,i)=>({id:`bad-version-${i}`,versions,expected:'incompatible-schema'})),
    {id:'multi-role',roles:['planner','expert'],expectedRoles:2},
    {id:'describe-tolerant',inputs:[null,{}, {futureField:true}],outputsEqual:true},
    {id:'operations-strict',operations:['Read','Validate','Save'],extraField:true,rejected:'invalid_input'},
    {id:'target-keyed',target:'owner-b',reportedOwner:'owner-a',expectedOwner:'owner-b'},
    {id:'status-filter',included:['running','degraded'],omitted:['disabled','failed','needs-configuration']},
    {id:'late-generation',generationOneCompletesLast:true,expected:'drop-old-result'},
    {id:'read-cancelled',signalAborted:true,expected:'cancelled'},
    {id:'save-unmount',unmountAfterDispatch:true,expectedAbortCalls:0,expectedSaveCalls:1},
    {id:'save-response-loss',freshReadSameIntentAndOwnedFields:true,expected:'reconciled',expectedSaveCalls:1},
    {id:'fingerprint-changed-by-other-writer',freshReadDifferentIntent:true,expected:'unknown-or-conflicting',expectedSaveCalls:1},
  ],
  ownership: [
    {id:'read-no-write-no-catalog',expectedWrites:0,expectedCatalogCalls:0,eligibility:'unverified'},
    {id:'validate-no-write',expectedWrites:0},
    {id:'raw-multi-key-conflict',interveningWrites:['instructions','legacyProvider'],expected:'conflict',expectedWrites:0},
    {id:'narrow-selection-save',preserved:['additionalInstructions','permissionMode'],changed:'selection'},
    {id:'central-reset-with-instructions',expected:'owner-fields-would-be-lost'},
    {id:'local-combined-save',mayEdit:'additionalInstructions',requiresSameFingerprint:true},
    {id:'invocation-no-route',eligibility:'deferred',shapeValid:true,staticOffered:true,expected:'saved'},
    {id:'invocation-invalid-sample',eligibility:'invalid-warning',storageRoute:'owner-global',expected:'saved'},
    {id:'static-blocked-save',shapeValid:true,expected:'rejected'},
    {id:'destination-reset-unavailable',choice:{kind:'inherit'},catalogUnavailable:true,ownedFieldsEmpty:true,expected:'saved'},
  ],
  controls: [
    {id:'collapsed',reads:0,catalogCalls:0,pickerMounts:0,saves:0},
    {id:'expanded',reads:1,catalogCalls:0,pickerMounts:0,saves:0,eligibility:'unverified'},
    {id:'invalid-retained',pickerMountsBeforeReplace:0,savesOnReconciliation:0},
    {id:'per-field-inherit',editing:'model',inherited:['providerId','reasoningLevel'],emittedKeys:['model']},
    {id:'fixed-provider-entry',allowProviderChange:false,offeredFields:['model','reasoningLevel']},
    {id:'explicit-other-slot-owner',slot:'a',clientTarget:'b',allRpcTargets:['b']},
    {id:'prepopulated-composer',before:{providerId:'p',model:'m',reasoningLevel:'high',serviceTier:'fast'},afterDisplay:'identical',afterIntentionalPickerEditing:'identical',ownerSavesUntilSave:0},
  ],
};
export const nativeErrors = [
  {status:404,body:{error:{code:'unknown_method'}},expected:'absent'},
  {status:404,body:{ok:false,error:'Unknown plugin: gone'},expected:'vanished'},
  {status:404,body:{error:{code:'not_found'}},expected:'host-incompatible'},
  {status:503,body:{ok:false,error:'plugin "b" is not running (status: disabled)'},expected:'unavailable'},
  {status:503,body:{ok:false,error:'Service temporarily unavailable'},expected:'transient'},
  {status:400,body:{error:{code:'invalid_input'}},expected:'incompatible'},
  {status:500,body:{error:{code:'invalid_output'}},expected:'incompatible'},
  {status:500,body:{error:{code:'other'}},expected:'owner-error'},
  {status:401,body:'denied',expected:'unauthorized'}, {status:403,body:'denied',expected:'unauthorized'},
  {name:'AbortError',expected:'cancelled'}, {name:'TimeoutError',expected:'transient'},
];
