import assert from "node:assert/strict";
import { test } from "node:test";
import { JSDOM } from "jsdom";
import { createDecorations } from "../decorations.ts";
import type { Stamp } from "../timing.ts";
import { findTimingPane } from "../pane.ts";

const stamp = (rowId: string, latest = false): Stamp => ({ rowId, kind: "user", at: Date.now() - 65_000,
  previousUserAt: null, previousFinishAt: null, nextUserAt: null, latest, status: null });
const flush = () => new Promise(resolve => setTimeout(resolve, 0));
test("1000 historical rows: streaming text causes no refresh, scans, or minute timers", async () => {
  const dom = new JSDOM(`<main>${Array.from({ length: 1000 }, (_, i) => `<div data-timeline-row-id="r${i}"><p>text</p></div>`).join("")}</main>`, { pretendToBeVisual: true });
  const root = dom.window.document.querySelector("main")!;
  let refreshes = 0;
  const timers: number[] = [];
  dom.window.setTimeout = ((_fn: unknown, delay: number) => { timers.push(delay); return 1; }) as typeof dom.window.setTimeout;
  const controller = createDecorations(root, () => refreshes++);
  controller.update(Array.from({ length: 1000 }, (_, i) => stamp(`r${i}`)));
  await flush();
  assert.equal(refreshes, 0);
  let scans = 0;
  root.querySelectorAll = (() => { scans++; throw new Error("unexpected full scan"); }) as typeof root.querySelectorAll;
  for (let i = 0; i < 100; i++) root.firstElementChild!.firstElementChild!.textContent = `stream ${i}`;
  await flush();
  assert.equal(scans, 0);
  assert.equal(refreshes, 0);
  assert.equal(timers.length, 1); // One calendar rollover, never one per row.
  const now = new Date();
  const midnight = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1).getTime();
  assert.ok(Math.abs(timers[0]! - (midnight - Date.now())) < 2_000);
  controller.dispose();
  assert.equal(root.firstElementChild!.children.length, 1);
  dom.window.close();
});
test("windowing, duplicate updates, pane isolation, disposal and remount", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a">A</div></main><aside><div data-timeline-row-id="b">B</div></aside>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  const root = doc.querySelector("main")!;
  let refreshes = 0;
  const controller = createDecorations(root, () => refreshes++);
  controller.update([stamp("a"), stamp("b")]);
  controller.update([stamp("a"), stamp("b")]);
  await flush();
  assert.equal(doc.querySelectorAll("[data-message-timings-nerd]").length, 1);
  doc.querySelector("aside")!.append(doc.createElement("section"));
  await flush();
  assert.equal(refreshes, 0);
  const row = root.firstElementChild as HTMLElement;
  row.dataset.timelineWindowedRealized = "false";
  await flush();
  assert.equal(doc.querySelectorAll("[data-message-timings-nerd]").length, 0);
  row.dataset.timelineWindowedRealized = "true";
  await flush();
  assert.equal(doc.querySelectorAll("[data-message-timings-nerd]").length, 1);
  controller.dispose();
  controller.update([stamp("a")]);
  assert.equal(doc.querySelectorAll("[data-message-timings-nerd]").length, 0);
  const next = createDecorations(root, () => {});
  next.update([stamp("a")]);
  assert.equal(doc.querySelectorAll("[data-message-timings-nerd]").length, 1);
  next.dispose(); dom.window.close();
});
test("only the live footer changes at its deadline; hidden tabs disarm timers", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"></div><div data-timeline-row-id="b"></div></main>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  let scheduled: (() => void) | null = null;
  let hidden = false;
  Object.defineProperty(doc, "hidden", { get: () => hidden });
  dom.window.setTimeout = ((fn: () => void) => { scheduled = fn; return 1; }) as typeof dom.window.setTimeout;
  dom.window.clearTimeout = (() => { scheduled = null; }) as typeof dom.window.clearTimeout;
  const controller = createDecorations(doc.querySelector("main")!, () => {});
  controller.update([stamp("a"), stamp("b", true)]);
  await flush();
  const historical = doc.querySelector('[data-timeline-row-id="a"]')!;
  let writes = 0;
  const observer = new dom.window.MutationObserver(records => { writes += records.length; });
  observer.observe(historical, { subtree: true, attributes: true, childList: true, characterData: true });
  assert.ok(scheduled);
  (scheduled as () => void)();
  await flush();
  assert.equal(writes, 0);
  hidden = true; doc.dispatchEvent(new dom.window.Event("visibilitychange"));
  assert.equal(scheduled, null);
  hidden = false; doc.dispatchEvent(new dom.window.Event("visibilitychange"));
  assert.ok(scheduled);
  controller.dispose(); assert.equal(scheduled, null);
  observer.disconnect(); dom.window.close();
});

test("hosted sibling headers discover their own split pane; moved rows are released", async () => {
  const dom = new JSDOM('<section data-split-pane-id="left"><header><button></button></header><main data-conversation-collapsed="false"><div data-timeline-row-id="a"></div></main></section><section data-split-pane-id="right"><header><button></button></header><main data-conversation-collapsed="false"></main></section>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  const left = findTimingPane(doc.querySelector("button")!)!;
  assert.equal(left.dataset.splitPaneId, "left");
  assert.equal(findTimingPane(doc.querySelectorAll("button")[1]!)?.dataset.splitPaneId, "right");
  let refreshes = 0;
  const controller = createDecorations(left, () => refreshes++);
  controller.update([stamp("a")], ["a", "tool"]);
  const row = doc.querySelector('[data-timeline-row-id="a"]') as HTMLElement;
  row.dataset.timelineWindowedRealized = "false";
  await flush();
  row.dataset.timelineWindowedRealized = "true";
  await flush();
  const tool = doc.createElement("div"); tool.dataset.timelineRowId = "tool"; left.append(tool);
  await flush();
  assert.equal(refreshes, 0, "known windowed rows do not request history again");
  const outside = doc.querySelectorAll("main")[1]!;
  outside.append(row);
  await flush();
  assert.equal(row.querySelectorAll("[data-message-timings-nerd]").length, 0);
  controller.update([stamp("a")]);
  assert.equal(row.querySelectorAll("[data-message-timings-nerd]").length, 0);
  controller.dispose(); dom.window.close();
});

test("equal snapshots cause no DOM writes", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"></div></main>', { pretendToBeVisual: true });
  const root = dom.window.document.querySelector("main")!;
  const controller = createDecorations(root, () => {});
  const value = stamp("a");
  controller.update([value]);
  await flush();
  let writes = 0;
  const observer = new dom.window.MutationObserver(records => { writes += records.length; });
  observer.observe(root, { subtree: true, childList: true, attributes: true, characterData: true });
  controller.update([{ ...value }]);
  await flush();
  assert.equal(writes, 0);
  observer.disconnect(); controller.dispose(); dom.window.close();
});


test("host child replacement restores the same footer; queued attributes cannot decorate another pane", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"><p>host content</p></div></main><aside></aside>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  const root = doc.querySelector("main")!;
  const controller = createDecorations(root, () => {});
  controller.update([stamp("a")]);
  await flush();
  const row = root.firstElementChild!;
  const footer = row.querySelector("[data-message-timings-nerd]")!;
  const span = footer.firstElementChild;
  row.replaceChildren(doc.createElement("p"));
  await flush();
  assert.equal(row.querySelector("[data-message-timings-nerd]"), footer);
  assert.equal(footer.firstElementChild, span);
  doc.querySelector("aside")!.append(row);
  row.setAttribute("data-timeline-windowed-realized", "true");
  await flush();
  assert.equal(row.querySelector("[data-message-timings-nerd]"), null);
  controller.dispose(); dom.window.close();
});

test("selected timing text survives refresh and catches up without replacing its text node", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"></div></main>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  const controller = createDecorations(doc.querySelector("main")!, () => {});
  const first = stamp("a", true);
  controller.update([first]);
  const span = doc.querySelector(".message-timings-nerd__age")!;
  const text = span.firstChild;
  const selection = doc.getSelection()!;
  selection.selectAllChildren(span);
  const selected = selection.toString();
  controller.update([{ ...first, at: first.at! - 120_000 }]);
  assert.equal(selection.toString(), selected);
  assert.equal(span.firstChild, text);
  selection.removeAllRanges(); doc.dispatchEvent(new dom.window.Event("selectionchange"));
  await flush();
  assert.notEqual(span.textContent, selected);
  assert.equal(span.firstChild, text);
  controller.dispose(); dom.window.close();
});

test("hidden snapshots reconcile once on return; known history limits suppress futile older-row reads", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"></div></main>', { pretendToBeVisual: true });
  const doc = dom.window.document;
  const root = doc.querySelector("main")!;
  let hidden = false; let requests = 0;
  Object.defineProperty(doc, "hidden", { get: () => hidden });
  const controller = createDecorations(root, () => requests++);
  const first = stamp("a");
  controller.update([first], ["a"], "a");
  await flush();
  const footer = root.querySelector("[data-message-timings-nerd]")!;
  const text = footer.textContent;
  hidden = true;
  controller.update([{ ...first, at: first.at! - 3_600_000 }], ["a"], "a");
  assert.equal(footer.textContent, text);
  hidden = false; doc.dispatchEvent(new dom.window.Event("visibilitychange"));
  assert.notEqual(footer.textContent, text);
  const older = doc.createElement("div"); older.dataset.timelineRowId = "older"; root.prepend(older);
  await flush(); assert.equal(requests, 0);
  const newer = doc.createElement("div"); newer.dataset.timelineRowId = "newer"; root.append(newer);
  await flush(); assert.equal(requests, 1);
  controller.dispose(); dom.window.close();
});

test("decoration errors clean up once and cannot escape subsequent observer callbacks", async () => {
  const dom = new JSDOM('<main><div data-timeline-row-id="a"></div></main>', { pretendToBeVisual: true });
  const root = dom.window.document.querySelector("main")!;
  let errors = 0;
  const controller = createDecorations(root, () => {}, () => errors++);
  root.firstElementChild!.append = () => { throw new Error("host changed while painting"); };
  assert.doesNotThrow(() => controller.update([stamp("a")]));
  assert.equal(errors, 1);
  root.firstElementChild!.setAttribute("data-timeline-windowed-realized", "true");
  await flush();
  controller.update([stamp("a")]); controller.dispose();
  assert.equal(errors, 1);
  assert.equal(root.querySelectorAll("[data-message-timings-nerd]").length, 0);
  dom.window.close();
});
