import { acceptanceMode, check, controlledClock, invalidBindingResult, isolatedNegativeControls, loadProductionBinding, missingBindingResult, requireMethods, sourceLimit, suiteResult } from "../browser/acceptance-binding.mjs";
const fixture = Object.freeze({ executionId: "analytics-exec_composition_fixture_abcdefghijklmnop", datumKey: "analytics-datum_composition_fixture_abcdefghijklmnop_0" });
const required = ["openDashboard", "executeAgentQuery", "executeVariant", "openMenu", "changeRange", "refresh", "editBundle", "exportMenuTarget", "readCoverage", "listBuiltins", "runAuthoredBundle", "dispose"];
function verify(t) { return [
  check("single-shared-execution-path", t.ui?.serviceInstanceId === t.agent?.serviceInstanceId && typeof t.ui?.serviceInstanceId === "string" ? "pass" : "fail", "UI and agent fixture calls observe one shared service instance"),
  check("frozen-range-identity", t.endpointA?.physicalExecutionKey !== t.endpointB?.physicalExecutionKey && t.scopeA?.physicalExecutionKey !== t.scopeB?.physicalExecutionKey ? "pass" : "fail", "concrete endpoint/scope variants receive distinct physical keys"),
  check("menu-survives-change", t.menu?.executionId === fixture.executionId && t.menu?.datumKey === fixture.datumKey && t.exported?.executionId === fixture.executionId && t.exported?.datumKey === fixture.datumKey ? "pass" : "fail", "captured menu execution and datum survive subsequent range/refresh/edit operations"),
  check("coverage-disclosure", Array.isArray(t.coverage?.incompleteReasons) && t.coverage.incompleteReasons.length > 0 && t.coverage.resultTruncated === false ? "pass" : "fail", "returned coverage is distinct from returned result truncation"),
  check("preserved-workflows", Array.isArray(t.builtins) && t.builtins.length >= 3 && t.authored?.executionId === fixture.executionId ? "pass" : "fail", "actual built-in listing and authored fixture execution remain available"),
]; }
export async function runSuite(options = {}) {
  const mode = acceptanceMode(options);
  if (mode === "instrument-self-test") { const p = { ui: { serviceInstanceId: "s1" }, agent: { serviceInstanceId: "s1" }, endpointA: { physicalExecutionKey: "p1" }, endpointB: { physicalExecutionKey: "p2" }, scopeA: { physicalExecutionKey: "p3" }, scopeB: { physicalExecutionKey: "p4" }, menu: { executionId: fixture.executionId, datumKey: fixture.datumKey }, exported: { executionId: fixture.executionId, datumKey: fixture.datumKey }, coverage: { incompleteReasons: ["backfill-in-progress"], resultTruncated: false }, builtins: ["a", "b", "c"], authored: { executionId: fixture.executionId } }; return suiteResult("composition", isolatedNegativeControls(verify, p, [{ id: "single-shared-execution-path", value: { ...p, agent: { serviceInstanceId: "s2" } } }, { id: "frozen-range-identity", value: { ...p, endpointB: { physicalExecutionKey: "p1" } } }, { id: "menu-survives-change", value: { ...p, exported: { executionId: fixture.executionId, datumKey: "old" } } }, { id: "coverage-disclosure", value: { ...p, coverage: { incompleteReasons: [], resultTruncated: false } } }, { id: "preserved-workflows", value: { ...p, authored: { executionId: "old" } } }]), [{ kind: "mode", value: mode }]); }
  const loaded = await loadProductionBinding(options, "composition"); if (loaded.kind === "missing") return missingBindingResult("composition", loaded.reason); const absent = requireMethods(loaded.binding, required); if (absent) return invalidBindingResult("composition", absent);
  const clock = controlledClock();
  try { const ui = await loaded.binding.openDashboard({ fixture, clock }); const agent = await loaded.binding.executeAgentQuery({ fixture, clock }); const endpointA = await loaded.binding.executeVariant({ fixture, endpoint: "a", scope: "scope-a", clock }); const endpointB = await loaded.binding.executeVariant({ fixture, endpoint: "b", scope: "scope-a", clock }); const scopeA = await loaded.binding.executeVariant({ fixture, endpoint: "a", scope: "scope-a", clock }); const scopeB = await loaded.binding.executeVariant({ fixture, endpoint: "a", scope: "scope-b", clock }); const menu = await loaded.binding.openMenu({ fixture, clock }); await loaded.binding.changeRange({ clock }); await loaded.binding.refresh({ clock }); await loaded.binding.editBundle({ clock }); const exported = await loaded.binding.exportMenuTarget({ target: menu, clock }); const coverage = await loaded.binding.readCoverage({ fixture, clock }); const builtins = await loaded.binding.listBuiltins({ clock }); const authored = await loaded.binding.runAuthoredBundle({ fixture, clock }); return suiteResult("composition", verify({ ui, agent, endpointA, endpointB, scopeA, scopeB, menu, exported, coverage, builtins, authored }), [sourceLimit(loaded.sources)]); }
  finally { await loaded.binding.dispose(); }
}
